name: CI (pytest in docker build)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-in-build:
    name: Build test target (runs pytest)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test target (fails if pytest fails)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: test
          # Use CPU wheels on hosted runners (default in your Dockerfile is cpu, but we set it explicitly)
          build-args: |
            TORCH_CHANNEL=cpu
          push: false
          # Speed up subsequent builds
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # OPTIONAL: build & push the runtime image after tests pass on main
  push-image:
    name: Push runtime image to GHCR
    needs: test-in-build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push runtime image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: runtime
          tags: |
            ghcr.io/${{ github.repository }}/myapp:sha-${{ github.sha }}
            ghcr.io/${{ github.repository }}/myapp:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
